### ISSUE TITLE
Scroll restoration not working on history.back() handler

### ISSUE THREAD

**Issue by AlbertKogan** [majido/scroll-restoration-proposal#13]
I try to set history.scrollRestoration = 'manual' in my history module (placed before </body> tag) but Chrome (47 Win8, 46 - 48 Fedora) still scroll page to top after history.back() handler fired.

**Comment by majido** [comment]
Is this navigation in the same document? Do you have a simple page where this issue is reproduced?
Here is an [example](http://output.jsbin.com/dizeko) page where it works as expected.

Two things to note:
1. Setting scroll restoration only impact current and future history entries. It does not affect previous entries in the history.
2. Manual scroll restoration does not mean a specific scroll position after navigation but rather that the browser will **not** attempt to **restore** any position. In particular, when navigating across two documents then leaving the scroll position to be at the page top after load is a valid (and expected in Chrome) behaviour. See second note [here](https://html.spec.whatwg.org/multipage/browsers.html#persisted-user-state-restoration).

**Comment by AlbertKogan** [comment]
Thanks for fast answer!

I make a little [screen cast](https://drive.google.com/file/d/0B2FaptO7fKO-TkQ5M2RzQ0hWZTg/view)   with page, that you gave. Is it expected behavior? I thought that browser should scroll to position, that was before pushState handler (Firefox, Safari and IE work that way).

So, do I understand correctly, that behavior when Chrome does not "save" screen position between different documents is a correct behavior, and if I want to set screen position, I need save in history coordinates of the page and scroll on popState manually?

**Comment by majido** [comment]
That is the expected behaviour.

Browser restoring the scroll position is the current _default_ behaviour (i.e. `auto`). Setting scroll restoration mode to `manual` tells the browser not to do that. It is meant for web apps that desire to implement their own scroll restoration logic and don't want to conflict with the browser implementation. If you want the default behaviour then you should not set ``history.scrollRestoration` and the browser will do the restoration for you.

Here is a [blog post](https://developers.google.com/web/updates/2015/09/history-api-scroll-restoration?hl=en) that provides some more details.
