### ISSUE TITLE
Impact on restoring form state

### ISSUE THREAD

**Issue by RByers** [majido/scroll-restoration-proposal#2]
Should cancelling restorestate prevent restoration of form state too?  If so, then can/should we expose the raw form state in the event somehow?  If not, what do we do if we decide we want to add such support later?

**Comment by majido** [comment]
I think it should not affect form state restoration. This is because there is already a good solution i.e., [autocomplete](https://html.spec.whatwg.org/multipage/forms.html#autofilling-form-controls:-the-autocomplete-attribute), for that which provides granular control over individual fields in a declarative way.

I don't see much value in providing a different way to do the same thing. We should just be clear in what is being prevented when 'restorestate' is prevented.

**Comment by RByers** [comment]
SGTM, thanks
